language: node_js
sudo: false
node_js:
- lts/*
- node
script: npm t
before_deploy: npm run docs
deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: update
    node_js: lts/*
